name: Build and Push Image to Staging and Production if image is safe
on: [ workflow_dispatch ]

env:
  QUAY_STAGING_URL: registry-quay-quay-staging.apps.ocp.tfrbr.sandbox232.opentlc.com/david
  QUAY_PROD_URL: registry-quay-quay-production.apps.ocp.tfrbr.sandbox232.opentlc.com/david

# Required permissions for m2m authentication. Generates a JWT token for the workflow to use.
permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push image to staging Quay.io Registry
    runs-on: ubuntu-22.04
    outputs:
      image_ref: ${{ steps.push-to-staging-quay.outputs.registry-path }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image-staging
      uses: redhat-actions/buildah-build@v2
      with:
        image: myapp
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Push to Staging Quay.io registry
      id: push-to-staging-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image-staging.outputs.image }}
        tags: ${{ steps.build-image-staging.outputs.tags }}
        registry: ${{ env.QUAY_STAGING_URL }}
        username: ${{ secrets.QUAY_STAGING_USERNAME }}
        password: ${{ secrets.QUAY_STAGING_PASSWORD }}

    - name: Print image url
      env:
        IMAGE_REF: ${{ steps.push-to-staging-quay.outputs.registry-path }}
      run: |
        echo "Image pushed: ${IMAGE_REF}"

  rhacs-image-scan:
    name: Scan image with RHACS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Resolve image ref
        shell: bash
        run: echo "IMAGE_REF=${{ needs.build.outputs.image_ref }}" >> "$GITHUB_ENV"

      - name: Central Login
        uses: stackrox/central-login@v1
        with:
          endpoint: https://central-rhacs-operator.apps.ocp.tfrbr.sandbox232.opentlc.com:443
      - name: Install roxctl
        uses: stackrox/roxctl-installer-action@v1
        with:
          central-endpoint: ${{ env.CENTRAL_ENDPOINT }}
          central-token: ${{ env.ROX_API_TOKEN }}
        
      - name: Scan image with roxctl
        shell: bash
        run: |
          set -euo pipefail
          roxctl image scan --output=json --insecure-skip-tls-verify --image="${{ env.IMAGE_REF }}" > scan-results.json

      - name: Convert JSON to Markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: json_table_image_scan
        with:
          json_file_path: "scan-results.json"

      - name: Append to Step Summary
        run: echo "${{ steps.json_table_image_scan.outputs.table }}" >> $GITHUB_STEP_SUMMARY


      - name: Check image with roxctl
        shell: bash
        run: |
          set -euo pipefail
          roxctl image check --output=json --insecure-skip-tls-verify --image="${{ env.IMAGE_REF }}" > check-results.json

      - name: Convert JSON to Markdown
        uses: buildingcash/json-to-markdown-table-action@v1
        id: json_table_image_check
        with:
          json_file_path: "check-results.json"

      - name: Append to Step Summary
        run: echo "${{ steps.json_table_image_check.outputs.table }}" >> $GITHUB_STEP_SUMMARY

  push-to-prod:
    name: Push image to production Quay.io Registry
    runs-on: ubuntu-22.04
    needs: [build, rhacs-image-scan]
    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image-prod
      uses: redhat-actions/buildah-build@v2
      with:
        image: myapp
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image-prod.outputs.image }}
        tags: ${{ steps.build-image-prod.outputs.tags }}
        registry: ${{ env.QUAY_PROD_URL }}
        username: ${{ secrets.QUAY_PROD_USERNAME }}
        password: ${{ secrets.QUAY_PROD_PASSWORD }}

    - name: Print image url
      env:
        IMAGE_REF: ${{ steps.push-to-quay.outputs.registry-path }}
      run: |
        echo "Image pushed: ${IMAGE_REF}"
