name: Build and Push Image to Staging
on: [ workflow_dispatch ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-22.04
    outputs:
      image_ref: ${{ steps.push-to-quay.outputs.registry-path }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: myapp
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile


    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ secrets.QUAY_STAGING_URL }}
        username: ${{ secrets.QUAY_STAGING_USERNAME }}
        password: ${{ secrets.QUAY_STAGING_PASSWORD }}

    - name: Print image url
      env:
        IMAGE_REF: ${{ steps.push-to-quay.outputs.registry-path }}
      run: echo "Image pushed: ${IMAGE_REF}"

  rhacs-scan:
    name: Scan pushed image with RHACS
    needs: build
    uses: ./.github/workflows/rhacs-image-scan.yml
    secrets: inherit
    with:
      image: ${{ needs.build.outputs.image_ref }}
